package catalog

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
)

type bundleFile struct {
	Name string `json:"name"`
	Data []byte `json:"data"`
}

func encodeBundle(corpus *Corpus) (string, error) {
	files, err := MarshalCorpus(corpus)
	if err != nil {
		return "", err
	}
	ordered := []bundleFile{}
	for _, name := range []string{"coverage.json", "geometries.json", "manifest.json", "receipts.json"} {
		ordered = append(ordered, bundleFile{Name: name, Data: files[name]})
	}
	raw, err := CanonicalJSON(ordered)
	if err != nil {
		return "", err
	}
	var compressed bytes.Buffer
	writer, err := gzip.NewWriterLevel(&compressed, gzip.BestCompression)
	if err != nil {
		return "", err
	}
	writer.Name, writer.Comment = "", ""
	if _, err := writer.Write(raw); err != nil {
		return "", err
	}
	if err := writer.Close(); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(compressed.Bytes()), nil
}

func decodeBundle(encoded string) (*Corpus, error) {
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("embedded base64: %w", err)
	}
	reader, err := gzip.NewReader(bytes.NewReader(compressed))
	if err != nil {
		return nil, fmt.Errorf("embedded gzip: %w", err)
	}
	raw, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	if err := reader.Close(); err != nil {
		return nil, err
	}
	var ordered []bundleFile
	if err := json.Unmarshal(raw, &ordered); err != nil {
		return nil, err
	}
	files := map[string][]byte{}
	for _, file := range ordered {
		if _, exists := files[file.Name]; exists {
			return nil, fmt.Errorf("duplicate embedded file %q", file.Name)
		}
		files[file.Name] = file.Data
	}
	return DecodeCorpus(files)
}

func Embedded() (*Corpus, error) {
	return decodeBundle(embeddedCorpusBase64)
}

func EmbeddedSource(corpus *Corpus) ([]byte, error) {
	encoded, err := encodeBundle(corpus)
	if err != nil {
		return nil, err
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by corpuscompile; DO NOT EDIT.\n\npackage catalog\n\nconst embeddedCorpusBase64 = `")
	const width = 96
	for len(encoded) > 0 {
		n := width
		if len(encoded) < n {
			n = len(encoded)
		}
		source.WriteString(encoded[:n])
		encoded = encoded[n:]
		if len(encoded) > 0 {
			source.WriteByte('\n')
		}
	}
	source.WriteString("`\n")
	return source.Bytes(), nil
}
